# Generated by Django 4.1.2 on 2023-05-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyUIGame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='territory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='territory',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
