# Generated by Django 4.1.2 on 2023-05-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyUIGame', '0002_territory_description_territory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
