# Generated by Django 4.1.2 on 2023-05-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyUIGame', '0003_skill_description_skill_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapone',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weapone',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weapone',
            name='starts',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='weapone',
            name='substats',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
